**NUMPY**

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [1]:
import numpy as np

A = np.array([1, 2, 3, 7, 9, 10])
B = np.array([3, 4, 5, 6, 10, 12])

v_stacked = np.vstack([A, B])
h_stacked = np.hstack([A, B])

print(v_stacked)
print(h_stacked)

[[ 1  2  3  7  9 10]
 [ 3  4  5  6 10 12]]
[ 1  2  3  7  9 10  3  4  5  6 10 12]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [2]:
common = np.intersect1d(A, B)

print(common)

[ 3 10]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [3]:
mask = (A >= 5) & (A <= 10)
A_in_range = A[mask]
print(A_in_range)

[ 7  9 10]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

cond = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_filtered = iris_2d[cond]

print(iris_filtered[:5])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]


**PANDAS**

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv
('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

every_20th = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(every_20th.head())

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv
('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [6]:
cols = ['Min.Price', 'Max.Price']
df[cols] = df[cols].fillna(df[cols].mean())
print(df[cols].isna().sum())

Min.Price    0
Max.Price    0
dtype: int64


3. How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [7]:
df_rand = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows_sum_gt_100 = df_rand[df_rand.sum(axis=1) > 100]
print(rows_sum_gt_100.head())

    0   1   2   3
0  38  19  30  30
2  28  20  39  25
3  16  38  22  28
5  24  38  13  28
6  12  36  30  29
